# Generated by Django 3.0.14 on 2022-09-20 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_quality', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryoptions_validator',
            options={'managed': True, 'ordering': ('indicator',), 'verbose_name': 'Valid Category Option', 'verbose_name_plural': '  Categoryoptions'},
        ),
        migrations.AlterModelOptions(
            name='datasource_validator',
            options={'managed': True, 'ordering': ('indicator',), 'verbose_name': 'Valid Source', 'verbose_name_plural': '  Datasources'},
        ),
        migrations.AlterModelOptions(
            name='facts_datafilter',
            options={'managed': True, 'verbose_name': 'Filter', 'verbose_name_plural': '    Facts Filter'},
        ),
        migrations.AlterModelOptions(
            name='facts_dataframe',
            options={'managed': False, 'ordering': ('indicator_name',), 'verbose_name': 'Facts', 'verbose_name_plural': '   Facts Dataset'},
        ),
        migrations.AlterModelOptions(
            name='measuretypes_validator',
            options={'managed': True, 'ordering': ('indicator',), 'verbose_name': 'Valid Measure Type', 'verbose_name_plural': '  Measuretypes'},
        ),
        migrations.AlterUniqueTogether(
            name='dqainvaliddatasourceremarks',
            unique_together={('indicator_name', 'location', 'categoryoption', 'datasource', 'period')},
        ),
    ]
